# -----------------------------------------------------------
# Definitions
# -----------------------------------------------------------

stages:
  - Build
  - Test
  - Variants

include:
  - project: "netify.ai/public/netify-development-support/\
              netify-ci-templates"
    ref: master
    file:
      - /gitlab/common/global-variables.yml
      - /gitlab/agent/debian-variables.yml
      - /gitlab/agent/rhel-variables.yml
      - /gitlab/agent/build-templates.yml
      - /gitlab/agent/test-templates.yml
      - /gitlab/agent/variants-templates.yml
      - /gitlab/common/variants-templates.yml

variables:
  CI_DEBUG_TRACE: 'false'
  GIT_SUBMODULE_STRATEGY: recursive
  OS_EXTRA_PACKAGES: ''
  OS_REPOS: ''

# -----------------------------------------------------------
# Build
# -----------------------------------------------------------

# Debian Targets

Debian/10/x86-64:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: debian
    OS_VERSION: 10
    OS_IMAGE: "debian:10"
    OS_ARCH: amd64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES: flex

Debian/11/x86-64:
  extends: .debian_build
  tags:
    - docker
  variables:
    OS_NAME: debian
    OS_VERSION: 11
    OS_IMAGE: "debian:11"
    OS_ARCH: amd64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true

Debian/11/x86-32:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: debian
    OS_VERSION: 11
    OS_IMAGE: "i386/debian:11"
    OS_ARCH: i386
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES: byacc flex

Debian/11/ARM-32v5:
  extends: .debian_build
  when: manual
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: debian
    OS_VERSION: 11
    OS_IMAGE: "arm32v5/debian:11"
    OS_ARCH: "armel"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES: byacc flex

Debian/11/ARM-32v7:
  extends: .debian_build
  when: manual
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: debian
    OS_VERSION: 11
    OS_IMAGE: "arm32v7/debian:11"
    OS_ARCH: "armhf"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES: byacc flex

Debian/11/ARM-64v8:
  extends: .debian_build
  when: manual
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: debian
    OS_VERSION: 11
    OS_IMAGE: "arm64v8/debian:11"
    OS_ARCH: "arm64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES: byacc flex

# Ubuntu Targets

Ubuntu/20.04/x86-64:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: ubuntu
    OS_VERSION: focal
    OS_IMAGE: "ubuntu:20.04"
    OS_ARCH: amd64
    OS_ARCH_PATH:
      value: binary-$OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES: byacc

Ubuntu/22.04/x86-64:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: ubuntu
    OS_VERSION: jammy
    OS_IMAGE: "ubuntu:22.04"
    OS_ARCH: amd64
    OS_ARCH_PATH:
      value: binary-$OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES: byacc flex

# RedHat Targets

CentOS/7/x86-64:
  extends: .rhel_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: centos
    OS_VERSION: 7
    OS_IMAGE: "centos:7.9.2009"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true

Rocky Linux/8/x86-64:
  extends: .rhel_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: rockylinux
    OS_VERSION: 8
    OS_IMAGE: "rockylinux:8"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_REPOS: --enablerepo=powertools,epel

AlmaLinux/8/x86-64:
  extends: .rhel_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: almalinux
    OS_VERSION: 8
    OS_IMAGE: "almalinux:8"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_REPOS: --enablerepo=powertools,epel

AlmaLinux/9/x86-64:
  extends: .rhel_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_NAME: almalinux
    OS_VERSION: 9
    OS_IMAGE: "almalinux:9"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_REPOS: --enablerepo=crb

# OpenWrt Targets

OpenWrt/19.07/x86-64:
  extends: .openwrt_build
  when: manual
  tags:
    - docker
  variables:
    OS_NAME: debian
    OS_VERSION: 11
    OS_IMAGE: "debian:11"
    OS_ARCH: amd64
    OS_EXTRA_PACKAGES: ncurses-dev gawk unzip python
    OPENWRT_VERSION: 19.07.10
    OPENWRT_ARCH1: x86/64
    OPENWRT_ARCH2: x86-64
    OPENWRT_ARCH3: x86_64
    OPENWRT_SDK:
      value: "https://downloads.openwrt.org/releases/\
              ${OPENWRT_VERSION}/targets/${OPENWRT_ARCH1}/\
              openwrt-sdk-${OPENWRT_VERSION}-${OPENWRT_ARCH2}\
              _gcc-7.5.0_musl.Linux-${OPENWRT_ARCH3}.tar.xz"
      expand: true
    OPENWRT_CONFIG:
      value: "https://downloads.openwrt.org/releases/\
              ${OPENWRT_VERSION}/targets/${OPENWRT_ARCH1}/\
              config.buildinfo"
      expand: true

# -----------------------------------------------------------
# Test
# -----------------------------------------------------------

# RedHat Targets

CentOS/7/Test:
  extends: .rhel_test
  tags:
    - docker
  only:
    - tags
    - web
  needs:
    - CentOS/7/x86-64
  variables:
    OS_NAME: centos
    OS_VERSION: 7
    OS_IMAGE: "centos:7.9.2009"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_UUID: NE-CE-07-X1

AlmaLinux/8/Test:
  extends: .rhel_test
  tags:
    - docker
  only:
    - tags
    - web
  needs:
    - AlmaLinux/8/x86-64
  variables:
    OS_NAME: almalinux
    OS_VERSION: 8
    OS_IMAGE: "almalinux:8"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_UUID: NE-CE-08-X1

# -----------------------------------------------------------
# Variants
# -----------------------------------------------------------

# RedHat Targets

ClearOS/7/x86-64:
  extends: .rhel_variants
  tags:
    - docker
  only:
    - tags
    - web
  needs:
    - CentOS/7/Test
  variables:
    OS_NAME: clearos
    OS_SOURCE: centos
    OS_VERSION: 7
    OS_IMAGE: "centos:7"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true

NethServer/7/x86-64:
  extends: .rhel_variants
  tags:
    - docker
  only:
    - tags
    - web
  needs:
    - CentOS/7/Test
  variables:
    OS_NAME: nethserver
    OS_SOURCE: centos
    OS_VERSION: 7
    OS_IMAGE: "centos:7"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true

RHEL/7/x86-64:
  extends: .rhel_variants
  tags:
    - docker
  only:
    - tags
    - web
  needs:
    - CentOS/7/Test
  variables:
    OS_NAME: rhel
    OS_SOURCE: centos
    OS_VERSION: 7
    OS_IMAGE: "centos:7.9.2009"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true

RHEL/8/x86-64:
  extends: .rhel_variants
  tags:
    - docker
  only:
    - tags
    - web
  needs:
    - AlmaLinux/8/Test
  variables:
    OS_NAME: rhel
    OS_SOURCE: almalinux
    OS_VERSION: 8
    OS_IMAGE: "almalinux:8"
    OS_ARCH: x86_64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true

# Source Code Archive

Source Archive:
  extends: .pkg_source
  tags:
    - docker
  needs:
    - Debian/11/x86-64
  variables:
    OS_NAME: debian
    OS_VERSION: 11
    OS_IMAGE: "debian:11"
    OS_ARCH: amd64
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES: zlib1g-dev libpcap-dev
      libgoogle-perftools-dev
