# -------------------------------------------------------------------------
# Definitions
# -------------------------------------------------------------------------

stages:
#  - bootstrap
  - build
  - test

#variables:
#  CI_DEBUG_TRACE: "true"

# -------------------------------------------------------------------------
# Build stage
# -------------------------------------------------------------------------

# RPM OS
#-------

.rpmos_build: &rpmos_build_script
  stage: build
  tags:
    - docker
  image: $RPMOS_IMAGE
  before_script:
    # Manually pull in submodules, the GIT_SUBMODULE_STRATEGY variable in GitLab is quirky
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    # Build via autogen/autoconfigure - TODO: review with DS
    # - sudo yum -y install automake
    # - ./autogen.sh
    # - ./configure
    # - make dist
    # Build via raw source only
    - grep ^Version netifyd.spec | sed 's/.*[[:space:]]//' > /tmp/version
    - tar --exclude=.git --transform "s,^,netifyd-`cat /tmp/version`/," -czf netifyd-`cat /tmp/version`.tar.gz *
    # Build packages
    - mkdir -p result builds/$CI_PROJECT_NAME/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH logs/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH
    - rpmbuild -bs netifyd.spec --define "_sourcedir $PWD" --define "_srcrpmdir $PWD"
    - mock -v --old-chroot --resultdir=result *.src.rpm
    # Copy packages and logs to artifacts
    - grep -v DEBUG result/root.log
    - mv result/*rpm builds/$CI_PROJECT_NAME/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH/
    - mv result/*log logs/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH/
    - rm -rf result
    # Push build to master node
    - sudo yum -y install rsync
    - rsync -rtv builds/* master-mirror.egloo.ca::netify-builds/
  artifacts:
    when: always
    paths:
    - builds
    - logs
    expire_in: 1 day

centos 7 build:
  variables:
    RPMOS_IMAGE: "registry.gitlab.com/egloo.ca/os-manager/builder-image:os7"
    RPMOS_OS: "centos"
    RPMOS_VERSION: "7"
    RPMOS_ARCH: "x86_64"
  <<: *rpmos_build_script

centos 8 build:
  variables:
    RPMOS_IMAGE: "registry.gitlab.com/egloo.ca/os-manager/builder-image:os8"
    RPMOS_OS: "centos"
    RPMOS_VERSION: "8"
    RPMOS_ARCH: "x86_64"
  <<: *rpmos_build_script


# -------------------------------------------------------------------------
# Test stage
# -------------------------------------------------------------------------

# CentOS
#-------

.rpmos_test: &rpmos_test_script
  stage: test
  tags:
    - docker
  image: $RPMOS_IMAGE
  script:
    - yum -y install epel-release
    - yum -y --nogpgcheck localinstall builds/$CI_PROJECT_NAME/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH/netifyd-[0-9]*.*.$RPMOS_ARCH.rpm
    # yum returns exit code 0 even if target is corrupt or invalid, so verify with rpm
    - rpm -qV netifyd
    # CentOS is used for mirror port mode only
    - echo $RPMOS_UUID > /etc/netify.d/agent.uuid
    - echo NETIFYD_AUTODETECT="no" > /etc/sysconfig/netifyd
    - echo NETIFYD_EXTRA_OPTS="-t" >> /etc/sysconfig/netifyd
    - echo NETIFYD_INTNET="eth0" >> /etc/sysconfig/netifyd
    - netifyd --enable-sink
    # netifyd returns exit code 0 if --enable-sink fails.  Add extra test
    - grep "enable_sink.*=.*yes" /etc/netifyd.conf || exit 1
    - ( cmdpid=$BASHPID; (sleep 35; kill $cmdpid) & exec netifyd -d -I eth0 )
    - curl "https://manager.netify.ai/api/v1/deployment/agents/status/$RPMOS_UUID"

centos 7 test:
  variables:
    RPMOS_OS: "centos"
    RPMOS_VERSION: "7"
    RPMOS_IMAGE: "centos:7"
    RPMOS_ARCH: "x86_64"
    RPMOS_UUID: "NE-CE-07-X1"
  <<: *rpmos_test_script

centos 8 test:
  variables:
    RPMOS_OS: "centos"
    RPMOS_VERSION: "8"
    RPMOS_IMAGE: "centos:8"
    RPMOS_ARCH: "x86_64"
    RPMOS_UUID: "NE-CE-08-X1"
  <<: *rpmos_test_script
