# -------------------------------------------------------------------------
# Definitions
# -------------------------------------------------------------------------

stages:
#  - bootstrap
  - build
  - test
  - deploy

#variables:
#  CI_DEBUG_TRACE: "true"

# -------------------------------------------------------------------------
# Build stage
# -------------------------------------------------------------------------

# RPM OS
#-------

.rpmos_build: &rpmos_build_script
  stage: build
  tags:
    - docker
  image: $RPMOS_IMAGE
  before_script:
    # Manually pull in submodules, the GIT_SUBMODULE_STRATEGY variable in GitLab is quirky
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    # Build via autogen/autoconfigure - TODO: review with DS
    # - sudo yum -y install automake
    # - ./autogen.sh
    # - ./configure
    # - make dist
    # Build via raw source only - FIXME: extract version number
    - tar --exclude=.git --transform "s,^,netifyd-2.99/," -czf netifyd-2.99.tar.gz *
    # Build packages
    - mkdir -p result builds/$CI_PROJECT_NAME/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH logs/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH
    - rpmbuild -bs netifyd.spec --define "_sourcedir $PWD" --define "_srcrpmdir $PWD"
    - mock -v --old-chroot --resultdir=result *.src.rpm
    # Copy packages and logs to artifacts
    - grep -v DEBUG result/root.log
    - mv result/*rpm builds/$CI_PROJECT_NAME/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH/
    - mv result/*log logs/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH/
    - rm -rf result
    # Push build to master node
    - sudo yum -y install rsync
    - rsync -rtv builds/* master-mirror.egloo.ca::netify-builds/
  artifacts:
    when: always
    paths:
    - builds
    - logs
    expire_in: 1 day

centos 7 build:
  variables:
    RPMOS_IMAGE: "registry.gitlab.com/egloo.ca/os-manager/builder-image:os7"
    RPMOS_OS: "centos"
    RPMOS_VERSION: "7"
    RPMOS_ARCH: "x86_64"
  <<: *rpmos_build_script

centos 8 build:
  variables:
    RPMOS_IMAGE: "registry.gitlab.com/egloo.ca/os-manager/builder-image:os8"
    RPMOS_OS: "centos"
    RPMOS_VERSION: "8"
    RPMOS_ARCH: "x86_64"
  <<: *rpmos_build_script


# xBSD
#-----

.xbsd_build: &xbsd_build_script
  stage: build
  before_script:
    # Manually pull in submodules, the GIT_SUBMODULE_STRATEGY variable in GitLab is quirky
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    # Prep build directory
    - mkdir -p builds/$CI_PROJECT_NAME/$XBSD_OS/$XBSD_VERSION/$XBSD_ARCH logs/$CI_PROJECT_NAME/$XBSD_OS/$XBSD_VERSION/$XBSD_ARCH
    # Pretend that a build was successful - push it up to the master mirror builds directory
    - curl http://download.netify.ai/netify/freebsd/11.2/netifyd-2.99_1.txz -o builds/$CI_PROJECT_NAME/$XBSD_OS/$XBSD_VERSION/$XBSD_ARCH/netifyd-2.99_1.txz
    - rsync -rtv builds/* master-mirror.egloo.ca::netify-builds/

freebsd 11 build:
  tags:
    - freebsd11
  variables:
    XBSD_OS: "freebsd"
    XBSD_TAG: "freebsd11"
    XBSD_VERSION: "11.3"
    XBSD_ARCH: "x86_64"
  <<: *xbsd_build_script


# -------------------------------------------------------------------------
# Test stage
# -------------------------------------------------------------------------

# CentOS
#-------

.rpmos_test: &rpmos_test_script
  stage: test
  tags:
    - docker
  image: $RPMOS_IMAGE
  script:
    - yum -y install epel-release
    - yum -y --nogpgcheck localinstall builds/$CI_PROJECT_NAME/$RPMOS_OS/$RPMOS_VERSION/$RPMOS_ARCH/netifyd-[0-9]*.*.$RPMOS_ARCH.rpm
    # yum returns exit code 0 even if target is corrupt or invalid, so verify with rpm
    - rpm -qV netifyd
    # CentOS is used for mirror port mode only
    - echo $RPMOS_UUID > /etc/netify.d/agent.uuid
    - echo NETIFYD_AUTODETECT="no" > /etc/sysconfig/netifyd
    - echo NETIFYD_EXTRA_OPTS="-t" >> /etc/sysconfig/netifyd
    - echo NETIFYD_INTNET="eth0" >> /etc/sysconfig/netifyd
    - netifyd --enable-sink
    # netifyd returns exit code 0 if --enable-sink fails.  Add extra test
    - grep "enable_sink.*=.*yes" /etc/netifyd.conf || exit 1
    - ( cmdpid=$BASHPID; (sleep 35; kill $cmdpid) & exec netifyd -d -I eth0 )
    - curl "https://manager.netify.ai/api/v1/deployment/agents/status/$RPMOS_UUID"

centos 7 test:
  variables:
    RPMOS_OS: "centos"
    RPMOS_VERSION: "7"
    RPMOS_IMAGE: "centos:7"
    RPMOS_ARCH: "x86_64"
    RPMOS_UUID: "NE-CE-07-3C"
  <<: *rpmos_test_script

centos 8 test:
  variables:
    RPMOS_OS: "centos"
    RPMOS_VERSION: "8"
    RPMOS_IMAGE: "centos:8"
    RPMOS_ARCH: "x86_64"
    RPMOS_UUID: "NE-CE-08-3C"
  <<: *rpmos_test_script

#  ClearOS
#---------

clearos 7 test:
  stage: test
  tags:
    - docker
  image: centos:7
  script:
    # FIXME: this is not a real ClearOS 7 test, just a start
    - rpm -Uvh http://mirrors.egloo.ca/egloo/clearos/7/devel/staging/clearos-release-7-current.noarch.rpm
    - rpm --import http://download.netify.ai/netify/clearos/7/testing/RPM-GPG-KEY-netify
    - curl http://download.netify.ai/netify/clearos/7/netify.repo --output /etc/yum.repos.d/netify.repo
    - yum -y --nogpgcheck --enablerepo=clearos-centos,clearos-centos-updates,clearos-contribs-testing,netify-testing localinstall centos/7/x86_64/*.rpm

# OPNsense/pfSense
#-----------------

.xbsd_test: &xbsd_test_script
  stage: test
  script:
    - pkg add http://pkg.freebsd.org/freebsd:11:x86:64/release_3/All/libunwind-20170615.txz
    - pkg add http://pkg.freebsd.org/freebsd:11:x86:64/release_3/All/google-perftools-2.7.txz
    - pkg install -y rsync
    - rsync -v master-mirror.egloo.ca::netify-builds/$CI_PROJECT_NAME/freebsd/11.3/x86_64/netifyd-2.99_1.txz .
    - pkg add netifyd-2.99_1.txz
    # Set our Agent UUID
    - echo "$AGENT_UUID" > /usr/local/etc/netify.d/agent.uuid
    - netifyd --enable-sink
    # netifyd returns exit code 0 if --enable-sink fails.  Add extra test
    - grep "enable_sink.*=.*yes" /usr/local/etc/netifyd.conf || exit 1
    - ( cmdpid=$BASHPID; (sleep 35; kill $cmdpid) & exec netifyd -d -I em1 )
    - curl "https://manager.netify.ai/api/v1/deployment/agents/status/$AGENT_UUID"
    - service netifyd onestart
    - netifyd --status
    - ps afx | grep netify

pfsense 2.4.x test:
  tags:
    - pfsense24
  variables:
    AGENT_UUID: "NE-PF-24-XC"
  <<: *xbsd_test_script

opnsense 19.7 test:
  tags:
    - opnsense197
  variables:
    AGENT_UUID: "NE-OP-19-XC"
  <<: *xbsd_test_script


# -------------------------------------------------------------------------
# Deploy
# -------------------------------------------------------------------------

clearos 7 deploy:
  stage: deploy
  tags:
    - docker
  image: centos:7
  script:
    - ls # build testing repos and rsync to master server?
