image: gcc:6.1

clone:
  depth: 1

pipelines:
  default:
    - step:
        name: Test build
        script:
          - git submodule update --init --recursive
          - ./autogen.sh
          - ./configure
          - make
  tags:
      v*:
      - step:
          name: Release build
          script:
            - git submodule update --init --recursive
            - ./autogen.sh
            - ./configure
            - make
