# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

clone:
  depth: 1

pipelines:
  tags:
      v*:
        - step:
          name: Release Build
          script:
            - git submodule update --init --recursive
            - ./autogen.sh
            - ./configure
            - make
