# Source package
#---------------

.pkg_source:
  stage: package
  image: $OS_IMAGE
  before_script:
    # Manually pull in submodules, the GIT_SUBMODULE_STRATEGY variable in GitLab is quirky
    - apt update
    - env DEBIAN_FRONTEND=noninteractive apt install -y git
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    # Build environment
    - apt update
    - env DEBIAN_FRONTEND=noninteractive apt install -y rsync debhelper autoconf automake bc bison build-essential coreutils flex libtool wget pkg-config git
    - env DEBIAN_FRONTEND=noninteractive apt install -y libcurl4-openssl-dev libmnl-dev libncurses5-dev libnetfilter-conntrack-dev libpcap-dev libgoogle-perftools-dev libtool zlib1g-dev systemd $OS_EXTRA_PACKAGES
    # Build packages
    - ./autogen.sh
    - ./configure --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --sysconfdir=/etc --localstatedir=/var
    - make dist-git
    - sha256sum > sha256.sum
    - sha512sum > sha512.sum
    # Copy packages to mirror
    - mkdir -p builds/netify/source/
    - mv -v *.tar.gz *.sum *.distinfo builds/netify/source/
    # Push build to master node
    - if [ -n "$CI_COMMIT_TAG" ]; then rsync -rtv builds/* master-mirror.netify-backend.gcp::netify/; fi
  artifacts:
    when: always
    paths:
    - builds
    expire_in: 1 day
