# CentOS
#-------

.rpmos_variants:
  stage: variants
  image: $RPMOS_IMAGE
  script:
    # Copy packages to mirror
    #- mkdir -p builds/netify/$RPMOS_OS/$RPMOS_VERSION/devel/$RPMOS_ARCH
    #- mkdir -p builds/netify/$RPMOS_OS/$RPMOS_VERSION/devel/source
    find builds
    # Push build to master node
    #- rsync -rtv builds/* master-mirror.c.netify-ai.internal::netify/
